# Generated by Django 5.2.3 on 2025-06-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
